services:

  postgre:
    build:
      context: ./PostgreSQL
      dockerfile: Dockerfile
    hostname: postgres
    ports:
      - "5000:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DATABASE_URL: postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_DATABASE}
    restart: on-failure
    networks:
      - databases

  mongo:
    image: mongo:latest
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - databases
    volumes:
      - ./MongoDB/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - databases

  python-redis-app:
    build: 
      context: ./Redis
      dockerfile: Dockerfile
    container_name: python-redis-app
    depends_on:
      - redis
    networks:
      - databases

networks:
  databases:
    external: true
    name: databases